package org.jormungandr.jupyter.model

import java.util.UUID

/**
 * Supported Jupyter cell types.
 */
enum class CellType(val value: String) {
    CODE("code"),
    MARKDOWN("markdown"),
    RAW("raw");

    companion object {
        fun fromString(type: String?): CellType = when (type?.lowercase()) {
            "markdown" -> MARKDOWN
            "raw" -> RAW
            else -> CODE
        }
    }
}

/**
 * Polymorphic representation of a Jupyter cell output.
 */
sealed class CellOutput {
    /**
     * Standard console stream output (stdout or stderr).
     */
    data class StreamOutput(
        val name: String,
        val text: String
    ) : CellOutput()

    /**
     * Return value from code execution.
     */
    data class ExecuteResultOutput(
        val executionCount: Int,
        val data: Map<String, Any>,
        val metadata: Map<String, Any> = emptyMap()
    ) : CellOutput() {
        fun getPlainText(): String? = data["text/plain"]?.toString()
        fun getHtml(): String? = data["text/html"]?.toString()
        fun getPngBase64(): String? = data["image/png"]?.toString()
    }

    /**
     * Rich MIME display data generated by display() or plotting libraries.
     */
    data class DisplayDataOutput(
        val data: Map<String, Any>,
        val metadata: Map<String, Any> = emptyMap()
    ) : CellOutput() {
        fun getPlainText(): String? = data["text/plain"]?.toString()
        fun getHtml(): String? = data["text/html"]?.toString()
        fun getPngBase64(): String? = data["image/png"]?.toString()
    }

    /**
     * Execution exception and traceback.
     */
    data class ErrorOutput(
        val ename: String,
        val evalue: String,
        val traceback: List<String>
    ) : CellOutput()
}

/**
 * Reply in a cell comment discussion thread.
 */
data class CellCommentReply(
    val id: String = UUID.randomUUID().toString(),
    val author: String,
    val text: String,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Threaded cell comment attached to a notebook cell.
 * Persisted in cell metadata under the "comments" key.
 */
data class CellComment(
    val id: String = UUID.randomUUID().toString(),
    val author: String,
    val text: String,
    val timestamp: Long = System.currentTimeMillis(),
    var resolved: Boolean = false,
    val replies: MutableList<CellCommentReply> = mutableListOf()
)

/**
 * Individual cell inside a Jupyter Notebook.
 */
data class NotebookCell(
    val id: String = UUID.randomUUID().toString(),
    var cellType: CellType = CellType.CODE,
    var source: String = "",
    var executionCount: Int? = null,
    val outputs: MutableList<CellOutput> = mutableListOf(),
    val comments: MutableList<CellComment> = mutableListOf(),
    val metadata: MutableMap<String, Any> = mutableMapOf(),
    @Transient var isExecuting: Boolean = false
) {
    fun clearOutputs() {
        outputs.clear()
        executionCount = null
    }

    fun addComment(author: String, text: String): CellComment {
        val comment = CellComment(author = author, text = text)
        comments.add(comment)
        return comment
    }
}

/**
 * Kernel specification recorded in notebook metadata.
 */
data class KernelSpecMetadata(
    var name: String = "python3",
    var displayName: String = "Python 3 (ipykernel)",
    var language: String = "python"
)

/**
 * Language information recorded in notebook metadata.
 */
data class LanguageInfoMetadata(
    var name: String = "python",
    var version: String = "3.x",
    var pygmentsLexer: String = "ipython3",
    var codemirrorMode: Map<String, Any> = mapOf("name" to "ipython", "version" to 3),
    var fileExtension: String = ".py"
)

/**
 * Global notebook metadata dictionary.
 */
data class NotebookMetadata(
    var kernelspec: KernelSpecMetadata = KernelSpecMetadata(),
    var languageInfo: LanguageInfoMetadata = LanguageInfoMetadata(),
    val custom: MutableMap<String, Any> = mutableMapOf()
)

/**
 * In-memory document model representing a full Jupyter Notebook (.ipynb).
 */
data class NotebookModel(
    val cells: MutableList<NotebookCell> = mutableListOf(),
    var metadata: NotebookMetadata = NotebookMetadata(),
    var nbformat: Int = 4,
    var nbformatMinor: Int = 5
) {
    fun addCell(type: CellType = CellType.CODE, source: String = "", atIndex: Int = -1): NotebookCell {
        val cell = NotebookCell(cellType = type, source = source)
        if (atIndex in 0..cells.size) {
            cells.add(atIndex, cell)
        } else {
            cells.add(cell)
        }
        return cell
    }

    fun removeCell(cellId: String): Boolean {
        return cells.removeIf { it.id == cellId }
    }

    fun moveCell(fromIndex: Int, toIndex: Int): Boolean {
        if (fromIndex !in cells.indices || toIndex !in cells.indices || fromIndex == toIndex) return false
        val cell = cells.removeAt(fromIndex)
        cells.add(toIndex, cell)
        return true
    }

    fun clearAllOutputs() {
        cells.forEach { it.clearOutputs() }
    }

    companion object {
        fun createDefaultPythonNotebook(): NotebookModel {
            val model = NotebookModel()
            model.addCell(
                CellType.MARKDOWN,
                "# Welcome to Jörmungandr Jupyter Studio 🐍\nInteractive Data Science, Analytics, and live kernel execution."
            )
            model.addCell(
                CellType.CODE,
                "import sys\nprint(f\"Python {sys.version} ready on Jörmungandr!\")"
            )
            return model
        }
    }
}
